{% set name = "cron-descriptor" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cron_descriptor-{{ version }}.tar.gz
  sha256: 443ccd21a36a7fc9464a42472199cbdbc0d86b09021af1a8dd1595e4c391d85e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions
    - python >={{ python_min }}

test:
  imports:
    - cron_descriptor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Salamek/cron-descriptor
  summary: A Python library that converts cron expressions into human readable strings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
