{% set name = "cron-descriptor" %}
{% set version = "1.2.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cron_descriptor-{{ version }}.tar.gz
  sha256: 6cfa0b5cdeda6af8af1eb501479dddc23deef9d2285cd8712afa4597569c990f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - cron_descriptor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Salamek/cron-descriptor
  summary: A Python library that converts cron expressions into human readable strings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
