{% set name = "cron-descriptor" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cron_descriptor-{{ version }}.tar.gz
  sha256: 7b1a00d7d25d6ae6896c0da4457e790b98cba778398a3d48e341e5e0d33f0488

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - cron_descriptor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Salamek/cron-descriptor
  summary: A Python library that converts cron expressions into human readable strings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
